// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9GSUB-CzsK2ls9zgi0jz7d39dZpb1Gck',
    appId: '1:25474086383:web:0284716aa4a782c44e721a',
    messagingSenderId: '25474086383',
    projectId: 'pharmacy-388f0',
    authDomain: 'pharmacy-388f0.firebaseapp.com',
    storageBucket: 'pharmacy-388f0.appspot.com',
    measurementId: 'G-039VRPF2GN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnAwMEaxHnsglpLJhbRu2Se55U4m6UbZM',
    appId: '1:25474086383:android:0421070974b9ca3c4e721a',
    messagingSenderId: '25474086383',
    projectId: 'pharmacy-388f0',
    storageBucket: 'pharmacy-388f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAdzyEPwDoeJTSHwZjpG7nibzkY5BnZ7k',
    appId: '1:25474086383:ios:3fb187309fe321934e721a',
    messagingSenderId: '25474086383',
    projectId: 'pharmacy-388f0',
    storageBucket: 'pharmacy-388f0.appspot.com',
    iosBundleId: 'com.example.phrmacySystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAdzyEPwDoeJTSHwZjpG7nibzkY5BnZ7k',
    appId: '1:25474086383:ios:3fb187309fe321934e721a',
    messagingSenderId: '25474086383',
    projectId: 'pharmacy-388f0',
    storageBucket: 'pharmacy-388f0.appspot.com',
    iosBundleId: 'com.example.phrmacySystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9GSUB-CzsK2ls9zgi0jz7d39dZpb1Gck',
    appId: '1:25474086383:web:0284716aa4a782c44e721a',
    messagingSenderId: '25474086383',
    projectId: 'pharmacy-388f0',
    authDomain: 'pharmacy-388f0.firebaseapp.com',
    storageBucket: 'pharmacy-388f0.appspot.com',
    measurementId: 'G-039VRPF2GN',
  );
}
