// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsEhOH-WBVaTV_wKXUfBMZGHUl7kJazMk',
    appId: '1:956703448547:web:de40359f898a002e6194d6',
    messagingSenderId: '956703448547',
    projectId: 'pharmacy-system-5f559',
    authDomain: 'pharmacy-system-5f559.firebaseapp.com',
    storageBucket: 'pharmacy-system-5f559.appspot.com',
    measurementId: 'G-7J2NQQF4DR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBF4wQqIc6QxWDLFsO8mntgsePAON59PM',
    appId: '1:956703448547:android:2d52ecbe00968dc16194d6',
    messagingSenderId: '956703448547',
    projectId: 'pharmacy-system-5f559',
    storageBucket: 'pharmacy-system-5f559.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPbzi5Ugk5baurm-nW5re5fUCdpwMvPIY',
    appId: '1:956703448547:ios:d7999240ea566d876194d6',
    messagingSenderId: '956703448547',
    projectId: 'pharmacy-system-5f559',
    storageBucket: 'pharmacy-system-5f559.appspot.com',
    iosBundleId: 'com.example.phrmacySystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPbzi5Ugk5baurm-nW5re5fUCdpwMvPIY',
    appId: '1:956703448547:ios:d7999240ea566d876194d6',
    messagingSenderId: '956703448547',
    projectId: 'pharmacy-system-5f559',
    storageBucket: 'pharmacy-system-5f559.appspot.com',
    iosBundleId: 'com.example.phrmacySystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsEhOH-WBVaTV_wKXUfBMZGHUl7kJazMk',
    appId: '1:956703448547:web:a4ac0c601a95b0ab6194d6',
    messagingSenderId: '956703448547',
    projectId: 'pharmacy-system-5f559',
    authDomain: 'pharmacy-system-5f559.firebaseapp.com',
    storageBucket: 'pharmacy-system-5f559.appspot.com',
    measurementId: 'G-0TGJE5MX89',
  );
}
